app:
    resource: "@AppBundle/Controller/AppController.php"
    prefix: /
    type: annotation


hellcat_irc_bot_backend:
    resource: "@HellcatChatBotBackendBundle/Resources/config/routing.yml"
    prefix:   /botcfg

hellcat_chat_bot_api:
    resource: "@HellcatChatBotApiBundle/Resources/config/routing.yml"
    prefix:   /bapi

hellcat_twitch_toolbox:
    resource: "@HellcatTwitchToolboxBundle/Resources/config/routing.yml"
    prefix:   /toolbox
