security:

    providers:
        hc_local_db:
            id: hc_usertools.login_user_provider

        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            pattern: ^/user
            provider: hc_local_db
            hc_user: true

        index:
            pattern: ^/
            anonymous: ~
