security:

    providers:
        hc_userprovider:
            id: hc_usertools.login_user_provider

        hc_apiuserprovider:
            id: hc_usertools.api_user_provider

        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            pattern: ^/botctl
            provider: hc_userprovider
            hc_user: true

        api:
            pattern: ^/bapi
            provider: hc_apiuserprovider
            hc_apiuser: true

        toolbox:
            pattern: ^/toolbox
            provider: hc_userprovider
            hc_user: true

        index:
            pattern: ^/
            anonymous: ~
