bot_api_system_v1:
    resource: "@HellcatIrcBotBackendBundle/Controller/BotApi/V1/SystemController.php"
    prefix: /v1
    type: annotation

bot_api_chatcommand_v1:
    resource: "@HellcatIrcBotBackendBundle/Controller/BotApi/V1/ChatCommandController.php"
    prefix: /v1
    type: annotation
